import { PocTable } from "@/components/internal/PocTable";
import { ResourceCard } from "@/components/internal/ResourceCard";
import { Card, CardContent } from "@/components/ui/card";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>React India 2024</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex flex-col">
        <header className="bg-primary text-primary-foreground py-6">
          <div className="container mx-auto px-4">
            <h1 className="text-3xl font-bold">
              Nuances of Iframe: Lessons from Contentstack Live Preview
            </h1>
            <p>Presented at React India 2024 - Remote Edition</p>
          </div>
        </header>

        <main className="flex-grow container mx-auto px-4 py-8">
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">
              Welcome to the Companion Site
            </h2>
            <p className="text-lg text-muted-foreground">
              This site contains additional resources, slides, POC, and code for
              you to explore after the talk.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">
              Proofs of Concept (POCs)
            </h2>

            <p>
              The POCs hosted here simulates the behaviour and may not use the
              actual code. You can get the source code and run it locally to get
              the real data{" "}
            </p>
            <PocTable />
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">Presentation Slides</h2>
            <Card>
              <CardContent className="p-0">
                {/* <iframe
                  src="https://docs.google.com/presentation/d/e/2PACX-1vQmrymNWFltfprLl9IX-irRcmvjsL1ahOKAt8YTzuWTdcWnzpQf-ugMmYTh1rXujg/embed?start=false&loop=false&delayms=3000"
                  className="w-full aspect-video"
                  allowFullScreen
                ></iframe> */}
              </CardContent>
            </Card>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">
              Additional Resources
            </h2>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <ResourceCard
                title="History of Embedding Technologies"
                description="Learn about the history of embedding technologies and how they evolved over time."
                url="https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#a_short_history_of_embedding"
                cta="Learn More"
              />
              <ResourceCard
                title="Iframe"
                description="Learn about Iframe and how to use it in your web applications."
                url="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe"
                cta="Learn More"
              />

              <ResourceCard
                title="Intersection Observer v2"
                description="Intersection Observer v2 adds the capability to not only observe intersections per se, but to also detect if the intersecting element was visible at the time of intersection."
                url="https://web.dev/articles/intersectionobserver-v2"
                cta="Read the article"
              />
              <ResourceCard
                title="Intersection Observer coverage"
                description="Which browsers support Intersection Observer?"
                url="https://caniuse.com/intersectionobserver-v2"
                cta="Check the support"
              />
              <ResourceCard
                title="Intersection Observer Demo"
                description="A demo to show how Intersection Observer works."
                url="https://io-v2.glitch.me/"
                cta="View Demo"
              />
              <ResourceCard
                title="X-Frame-Options"
                description="Learn about the X-Frame-Options header and how it works."
                url="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options"
                cta="Learn More"
              />
              <ResourceCard
                title="Frame ancestors"
                description="Learn about the frame-ancestors directive in Content Security Policy."
                url="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors"
                cta="Learn More"
              />
              <ResourceCard
                title="Same Origin Policy"
                description="Learn about the Same Origin Policy and how it affects the web."
                url="https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy"
                cta="Learn More"
              />
              <ResourceCard
                title="Cross-Origin Resource Sharing (CORS)"
                description="Learn about Cross-Origin Resource Sharing and how it works."
                url="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"
                cta="Learn More"
              />
              <ResourceCard
                title="Post Message"
                description="Learn about Post Message and how to use it to communicate between iframes."
                url="https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage"
                cta="Learn More"
              />
              <ResourceCard
                title="Source code"
                description="The Source code of this site containing the POCs"
                url="https://github.com/deepak-kharah/talk-nuances-of-iframe"
                cta="Learn More"
              />
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              Tools used for the presentation
            </h2>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <ResourceCard
                title="Excalidraw"
                description="Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them."
                url="https://excalidraw.com/"
                cta="Visit website"
              />
            </div>
          </section>
        </main>

        <footer className="bg-muted py-6 mt-12">
          <div className="container mx-auto px-4 text-center text-muted-foreground">
            <p>&copy; 2023 Iframe Mastery Talk. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </>
  );
}
